# If normal players without special permissions are allowed to join
# Not implemented yet!
allow-join: true

# If the match is used for experimental or debugging purposes.
# Not implemented yet!
experimental: false

# If set to true, the game will use the competitive/ranked game rules
# Not implemented yet!
competitive: false

# If the game will translate text based on the player's Minecraft language
localization: true

# What match types are not allowed to be started
# Valid options are: 'normal', 'duo', 'chaos'
disallowed-types:
  - 'placeholder'
